from __future__ import annotations

"""Configuration for the exact entity/event VFX Director contract.

The retired recipe/macro selector is intentionally absent. Production VFX is
one authored Director response over accepted runtimeProgram pairs, with one
conditional Repair after deterministic validation failure.
"""

from infini_local.core.env_utils import env_bool, env_float, env_int


VFX_LLM_DIRECTOR_ENABLED = env_bool("INFINI_VFX_LLM_DIRECTOR", True)
VFX_LLM_DIRECTOR_MAX_SLOTS = env_int("INFINI_VFX_LLM_DIRECTOR_MAX_SLOTS", 5)
VFX_LLM_DIRECTOR_MAX_TOKENS = env_int("INFINI_VFX_LLM_DIRECTOR_MAX_TOKENS", 1800)
VFX_LLM_DIRECTOR_TEMPERATURE = env_float("INFINI_VFX_LLM_DIRECTOR_TEMPERATURE", 0.34)
VFX_LLM_REPAIR_TEMPERATURE = env_float("INFINI_VFX_LLM_REPAIR_TEMPERATURE", 0.12)
VFX_LLM_DIRECTOR_TIMEOUT = env_int("INFINI_VFX_LLM_DIRECTOR_TIMEOUT", 75)
VFX_LLM_DIRECTOR_REPAIR_ATTEMPTS = min(1, max(0, env_int("INFINI_VFX_LLM_DIRECTOR_REPAIR_ATTEMPTS", 1)))

VFX_RENDER_QUALITY = "Full"
VFX_EMERGENCY_MAX_PARTICLES_PER_TICK = env_int("INFINI_VFX_EMERGENCY_MAX_PARTICLES_PER_TICK", 240)
VFX_EMERGENCY_MAX_PARTICLES_TOTAL = env_int("INFINI_VFX_EMERGENCY_MAX_PARTICLES_TOTAL", 9000)
VFX_EMERGENCY_MAX_DRAW_CALLS = env_int("INFINI_VFX_EMERGENCY_MAX_DRAW_CALLS", 420)


__all__ = [
    "VFX_LLM_DIRECTOR_ENABLED",
    "VFX_LLM_DIRECTOR_MAX_SLOTS",
    "VFX_LLM_DIRECTOR_MAX_TOKENS",
    "VFX_LLM_DIRECTOR_TEMPERATURE",
    "VFX_LLM_REPAIR_TEMPERATURE",
    "VFX_LLM_DIRECTOR_TIMEOUT",
    "VFX_LLM_DIRECTOR_REPAIR_ATTEMPTS",
    "VFX_RENDER_QUALITY",
    "VFX_EMERGENCY_MAX_PARTICLES_PER_TICK",
    "VFX_EMERGENCY_MAX_PARTICLES_TOTAL",
    "VFX_EMERGENCY_MAX_DRAW_CALLS",
]
