// Generated by tools/generate_equipment_bounds.py; do not edit by hand.
#nullable enable
using System;

namespace InfiniCrafterLocal.Common.Models;

internal static class GeneratedEquipmentBounds
{
    internal static void Normalize(AccessorySpec a)
    {
        a.Endurance = Math.Clamp(a.Endurance, 0f, 0.75f);
        a.Defense = Math.Clamp(a.Defense, -100, 500);
        a.GenericCrit = Math.Clamp(a.GenericCrit, -100f, 100f);
        a.LifeRegen = Math.Clamp(a.LifeRegen, -120, 200);
        a.LightStrength = Math.Clamp(a.LightStrength, 0f, 1.5f);
        a.ManaRegen = Math.Clamp(a.ManaRegen, -120, 200);
        a.MaxLife = Math.Clamp(a.MaxLife, -500, 5000);
        a.MaxMana = Math.Clamp(a.MaxMana, -500, 5000);
        a.MinionSlots = Math.Clamp(a.MinionSlots, 0, 20);
        a.MovementSpeed = Math.Clamp(a.MovementSpeed, -0.9f, 3f);
        a.SentrySlots = Math.Clamp(a.SentrySlots, 0, 20);
        a.GenericDamage = Math.Clamp(a.GenericDamage, -0.9f, 3f);
    }

    internal static void Normalize(ArmorSpec a)
    {
        a.Defense = Math.Clamp(a.Defense, 0, 500);
        a.GenericCrit = Math.Clamp(a.GenericCrit, -100f, 100f);
        a.MaxLife = Math.Clamp(a.MaxLife, -500, 5000);
        a.MaxMana = Math.Clamp(a.MaxMana, -500, 5000);
        a.MovementSpeed = Math.Clamp(a.MovementSpeed, -0.9f, 3f);
        a.SetBonusLifeRegen = Math.Clamp(a.SetBonusLifeRegen, -120, 200);
        a.SetBonusMovementSpeed = Math.Clamp(a.SetBonusMovementSpeed, -0.9f, 3f);
        a.GenericDamage = Math.Clamp(a.GenericDamage, -0.9f, 3f);
        a.SetBonusGenericDamage = Math.Clamp(a.SetBonusGenericDamage, -0.9f, 3f);
    }

}
