from __future__ import annotations

from typing import Any

# AGENT MAP: deterministic authored runtimePlan golden cases for gameplay proof.
# These cases are compiler/provenance/gameplay-seam probes only: no LLM, no HTTP, no image backend.

GOLDEN_RUNTIME_CASES: list[dict[str, Any]] = [
{'caseId': 'melee_swing_onhit',
 'description': 'Melee swing weapon with explicit frostburn on-hit intent.',
 'input': {'category': 'weapon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'melee',
                                                       'damage': 18,
                                                       'useTimeTicks': 28}},
                                           {'fn': 'perform_melee_attack',
                                            'params': {'family': 'sword',
                                                       'movement': 'swing_arc',
                                                       'projectileShape': 'ember blade arc'}},
                                           {'fn': 'apply_on_hit_effect',
                                            'params': {'onHit': 'frostburn', 'debuffTime': 180}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile', 'apply_on_hit_effect'],
            'patchEquals': {'runtimeFamily': 'swing', 'delivery': 'swing', 'onHit': 'frostburn'},
            'authoredStatsEquals': {'resultKind': 'weapon', 'damageClass': 'melee', 'damage': 18, 'useTimeTicks': 28},
            'patchHasKeys': ['useStyleCode'],
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'swing',
                                     'delivery': 'swing',
                                     'onHit': 'frostburn',
                                     'weaponFamily': 'sword',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon', 'damageClass': 'melee', 'damage': 18, 'useTime': 28}}},
{'caseId': 'ranged_straight_shot',
 'description': 'Ranged bow-style straight shot with explicit projectile executor.',
 'input': {'category': 'weapon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'ranged',
                                                       'damage': 14,
                                                       'useTimeTicks': 26}},
                                           {'fn': 'fire_ranged_weapon',
                                            'params': {'family': 'bow',
                                                       'movement': 'straight',
                                                       'speed': 11,
                                                       'rangeTiles': 48,
                                                       'projectileShape': 'leaf arrow'}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile'],
            'patchEquals': {'runtimeFamily': 'shoot',
                            'delivery': 'shoot',
                            'movement': 'straight',
                            'weaponFamily': 'bow'},
            'authoredStatsEquals': {'resultKind': 'weapon',
                                    'damageClass': 'ranged',
                                    'damage': 14,
                                    'useTimeTicks': 26},
            'patchHasKeys': ['speed', 'rangeTiles', 'useStyleCode'],
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'shoot',
                                     'delivery': 'shoot',
                                     'movement': 'straight',
                                     'weaponFamily': 'bow',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon', 'damageClass': 'ranged', 'damage': 14, 'useTime': 26}}},
{'caseId': 'magic_cast_aura',
 'description': 'Magic beam staff intent lowered into cast runtime with bounded effect/on-hit fields.',
 'input': {'category': 'weapon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'magic',
                                                       'damage': 22,
                                                       'useTimeTicks': 32,
                                                       'manaCost': 8}},
                                           {'fn': 'cast_magic_weapon',
                                            'params': {'family': 'beam_staff',
                                                       'movement': 'laser',
                                                       'effect': 'fire',
                                                       'speed': 9,
                                                       'rangeTiles': 42,
                                                       'projectileShape': 'ruby beam'}},
                                           {'fn': 'apply_on_hit_effect',
                                            'params': {'onHit': 'electric', 'count': 2}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile', 'apply_on_hit_effect'],
            'patchEquals': {'runtimeFamily': 'cast',
                            'delivery': 'cast',
                            'movement': 'phase',
                            'effect': 'flame',
                            'onHit': 'lightning_arc'},
            'authoredStatsEquals': {'resultKind': 'weapon',
                                    'damageClass': 'magic',
                                    'damage': 22,
                                    'useTimeTicks': 32,
                                    'manaCost': 8},
            'patchHasKeys': ['rangeTiles'],
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'cast',
                                     'delivery': 'cast',
                                     'effect': 'flame',
                                     'onHit': 'lightning_arc',
                                     'weaponFamily': 'beam_staff',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon',
                                       'damageClass': 'magic',
                                       'damage': 22,
                                       'useTime': 32,
                                       'manaCost': 8}}},
{'caseId': 'summon_minion_safe',
 'description': 'Safe minion summon intent stays inside the bounded summon executor.',
 'input': {'category': 'summon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'summon',
                                                       'damage': 16,
                                                       'useTimeTicks': 34}},
                                           {'fn': 'summon_combat_entity',
                                            'params': {'family': 'minion',
                                                       'movement': 'orbit',
                                                       'shotCount': 1,
                                                       'projectileShape': 'clockwork moth'}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile'],
            'patchEquals': {'runtimeFamily': 'summon', 'delivery': 'summon', 'weaponFamily': 'minion'},
            'authoredStatsEquals': {'resultKind': 'weapon',
                                    'damageClass': 'summon',
                                    'damage': 16,
                                    'useTimeTicks': 34},
            'patchNotHasKeys': ['runtimeContractError', 'bossNpcType']},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'summon',
                                     'delivery': 'summon',
                                     'weaponFamily': 'minion',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon', 'damageClass': 'summon', 'damage': 16, 'useTime': 34}}},
{'caseId': 'accessory_runtime',
 'description': 'Accessory authoring compiles into explicit accessory stats, not weapon runtime.',
 'input': {'category': 'accessory',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'accessory', 'rarity': 3, 'value': 12000}},
                                           {'fn': 'accessory_effect',
                                            'params': {'archetype': 'ranger_support',
                                                       'sentrySlots': 1,
                                                       'manaCostReduction': 0.12,
                                                       'ammoSaveChance': 0.18,
                                                       'endurance': 0.08,
                                                       'armorPenetration': 6}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'accessory_effect'],
            'patchEquals': {'kind': 'accessory', 'maxStack': 1},
            'authoredStatsEquals': {'resultKind': 'accessory', 'rarity': 3, 'value': 12000},
            'patchNestedEquals': {'accessory': {'enabled': True,
                                                'sentrySlots': 1,
                                                'manaCostReduction': 0.12,
                                                'ammoSaveChance': 0.18,
                                                'endurance': 0.08,
                                                'armorPenetration': 6.0}},
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'accessory',
                    'attackEquals': {'enabled': False},
                    'gameplayEquals': {'kind': 'accessory', 'damage': 0, 'maxStack': 1},
                    'accessoryEquals': {'enabled': True, 'sentrySlots': 1}}},
{'caseId': 'armor_runtime',
 'description': 'Armor authoring compiles into explicit armor slot and bounded set/stat fields.',
 'input': {'category': 'armor',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'armor',
                                                       'armorSlot': 'body',
                                                       'defense': 9,
                                                       'rarity': 4}},
                                           {'fn': 'armor_effect',
                                            'params': {'armorSlot': 'body',
                                                       'archetype': 'summoner',
                                                       'minionSlots': 1,
                                                       'summonDamage': 0.12,
                                                       'setBonusText': 'Motes orbit the player.'}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'armor_effect'],
            'patchEquals': {'kind': 'armor', 'maxStack': 1, 'damage': 0},
            'authoredStatsEquals': {'resultKind': 'armor', 'armorSlot': 'body', 'defense': 9, 'rarity': 4},
            'patchNestedEquals': {'armor': {'enabled': True, 'slot': 'body', 'minionSlots': 1, 'summonDamage': 0.12}},
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'armor',
                    'attackEquals': {'enabled': False},
                    'gameplayEquals': {'kind': 'armor', 'damage': 0, 'maxStack': 1},
                    'armorEquals': {'enabled': True, 'slot': 'body', 'minionSlots': 1}}},
{'caseId': 'tool_mining_light',
 'description': 'Tool capability and authored light compile into concrete utility/runtime-light fields.',
 'input': {'category': 'tool',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'tool', 'damage': 7, 'useTimeTicks': 20}},
                                           {'fn': 'tool_capability',
                                            'params': {'pickPower': 65, 'axePower': 12, 'miningSpeedScale': 1.35}},
                                           {'fn': 'emit_light',
                                            'params': {'strength': 0.85, 'lightColorName': 'amber'}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'tool_capability', 'emit_light'],
            'patchEquals': {'pickPower': 65,
                            'axePower': 12,
                            'miningSpeedScale': 1.35,
                            'runtimeLightStrength': 0.85,
                            'runtimeLightColorName': 'amber'},
            'authoredStatsEquals': {'resultKind': 'tool', 'damage': 7, 'useTimeTicks': 20},
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'tool',
                    'attackEquals': {'enabled': False},
                    'gameplayEquals': {'kind': 'tool',
                                       'pickPower': 65,
                                       'axePower': 12,
                                       'miningSpeedScale': 1.35,
                                       'runtimeLightStrength': 0.85,
                                       'runtimeLightColorName': 'amber',
                                       'useTime': 20}}},
{'caseId': 'mobility_runtime',
 'description': 'Mobility call compiles into explicit blink fields and keeps safe-tile policy.',
 'input': {'category': 'tool',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'tool', 'useTimeTicks': 40}},
                                           {'fn': 'mobility_effect',
                                            'params': {'mode': 'blink_to_cursor',
                                                       'rangeTiles': 26,
                                                       'cooldownTicks': 180,
                                                       'safeTileOnly': True}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'mobility_effect'],
            'patchEquals': {'mobilityMode': 'blink_to_cursor',
                            'mobilityRangeTiles': 26,
                            'mobilityCooldownTicks': 180,
                            'mobilitySafeTileOnly': True},
            'authoredStatsEquals': {'resultKind': 'tool', 'useTimeTicks': 40},
            'patchNotHasKeys': ['runtimeContractError']},
 'expectGameplay': {'categoryEquals': 'tool',
                    'gameplayEquals': {'mobilityMode': 'blink_to_cursor',
                                       'mobilityRangeTiles': 26,
                                       'mobilityCooldownTicks': 180,
                                       'mobilitySafeTileOnly': True,
                                       'useTime': 40}}},
{'caseId': 'visual_only_cue',
 'description': 'Visual cue compiles as VFX metadata without inventing gameplay executor fields.',
 'input': {'category': 'weapon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'ranged',
                                                       'damage': 11,
                                                       'useTimeTicks': 30}},
                                           {'fn': 'fire_ranged_weapon',
                                            'params': {'family': 'gun',
                                                       'movement': 'straight',
                                                       'speed': 12,
                                                       'projectileShape': 'spark slug'}},
                                           {'fn': 'visual_effect_cue',
                                            'params': {'event': 'hit',
                                                       'rendererKind': 'impactRing',
                                                       'channel': 'impactShape',
                                                       'particleSystemId': 'pl:spark',
                                                       'duration': 12,
                                                       'importance': 'accent'}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile', 'visual_effect_cue'],
            'patchEquals': {'runtimeFamily': 'shoot', 'delivery': 'shoot', 'vfxCueCount': 1},
            'authoredStatsEquals': {'resultKind': 'weapon',
                                    'damageClass': 'ranged',
                                    'damage': 11,
                                    'useTimeTicks': 30},
            'patchHasKeys': ['vfxCues'],
            'patchNotHasKeys': ['runtimeContractError', 'worldEntitySpawn']},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'shoot',
                                     'delivery': 'shoot',
                                     'weaponFamily': 'gun',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon', 'damageClass': 'ranged', 'damage': 11, 'useTime': 30},
                    'gameplayNotHasKeys': ['worldEntitySpawn']}},
{'caseId': 'forbidden_world_entity',
 'description': 'Forbidden world/boss spawn intent is rejected while a safe minion summon remains executable.',
 'input': {'category': 'summon',
           'runtimePlan': {'engineCalls': [{'fn': 'set_item_stats',
                                            'params': {'resultKind': 'weapon',
                                                       'damageClass': 'summon',
                                                       'damage': 18,
                                                       'useTimeTicks': 30}},
                                           {'fn': 'summon_boss', 'params': {'family': 'eye_of_cthulhu'}},
                                           {'fn': 'summon_combat_entity',
                                            'params': {'family': 'boss', 'movement': 'orbit', 'shotCount': 1}},
                                           {'fn': 'summon_combat_entity',
                                            'params': {'family': 'minion', 'movement': 'orbit', 'shotCount': 1}}]}},
 'expect': {'requiredFunctions': ['set_item_stats', 'shoot_projectile'],
            'patchEquals': {'runtimeFamily': 'summon', 'delivery': 'summon', 'weaponFamily': 'minion'},
            'authoredStatsEquals': {'resultKind': 'weapon',
                                    'damageClass': 'summon',
                                    'damage': 18,
                                    'useTimeTicks': 30},
            'patchNotHasKeys': ['runtimeContractError', 'bossNpcType', 'worldEntitySpawn'],
            'rejectedReasonsContain': ['forbidden_world_entity_spawn'],
            'minRejectedCalls': 2},
 'expectGameplay': {'categoryEquals': 'weapon',
                    'attackEquals': {'enabled': True,
                                     'runtimeFamily': 'summon',
                                     'delivery': 'summon',
                                     'weaponFamily': 'minion',
                                     'runtimePlanAuthored': True},
                    'gameplayEquals': {'kind': 'weapon', 'damageClass': 'summon', 'damage': 18},
                    'gameplayNotHasKeys': ['bossNpcType', 'worldEntitySpawn']}},
]

__all__ = ["GOLDEN_RUNTIME_CASES"]
