from __future__ import annotations

"""Runtime dump discovery and lookup helpers.

Runtime dumps are optional JSONL files generated by the in-game /infinidump command.
They belong outside server.py because they are pure data-discovery/indexing logic, not
HTTP/combine orchestration.
"""

import json
from pathlib import Path
from typing import Any, Callable

from infini_local.core.env_utils import env_first, env_str


def runtime_dump_candidates(data_dir: Path, filename: str, explicit_env: str, legacy_env: str) -> list[Path]:
    candidates: list[Path] = []
    explicit = env_first((explicit_env, legacy_env), "")
    if explicit:
        candidates.append(Path(explicit))

    # Optional packaged/dev location, useful while hacking locally, but should not
    # be populated in normal public zips.
    candidates.append(data_dir / "runtime_dumps" / filename)

    home = Path.home()
    user_profile = Path(env_str("USERPROFILE", str(home)))
    docs_roots = [
        home / "Documents",
        user_profile / "Documents",
        user_profile / "OneDrive" / "Documents",
        user_profile / "OneDrive" / "Документы",
        home / "Документы",
    ]
    for docs in docs_roots:
        candidates.append(docs / "My Games" / "Terraria" / "tModLoader" / "InfiniCrafterLocal" / filename)

    out: list[Path] = []
    seen: set[str] = set()
    for c in candidates:
        key = str(c).lower()
        if key not in seen:
            seen.add(key)
            out.append(c)
    return out


def resolve_runtime_dump_path(data_dir: Path, filename: str, explicit_env: str, legacy_env: str) -> Path:
    candidates = runtime_dump_candidates(data_dir, filename, explicit_env, legacy_env)
    for c in candidates:
        if c.exists():
            return c
    return candidates[0]


def load_jsonl_index(path: Path, key_fields: tuple[str, ...]) -> tuple[list[dict[str, Any]], dict[Any, dict[str, Any]], dict[str, dict[str, Any]]]:
    rows: list[dict[str, Any]] = []
    by_type: dict[Any, dict[str, Any]] = {}
    by_full: dict[str, dict[str, Any]] = {}
    try:
        if not path.exists():
            return rows, by_type, by_full
        with path.open("r", encoding="utf-8-sig") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                if not isinstance(row, dict):
                    continue
                rows.append(row)
                if "type" in row:
                    by_type[row.get("type")] = row
                    try:
                        by_type[int(row.get("type"))] = row
                    except Exception:
                        pass
                fields = tuple(k for k in (key_fields or ()) if str(k).strip()) or ("sourceMod", "internalName")
                key_parts = [str(row.get(k, "")).strip().lower() for k in fields]
                if key_parts and any(key_parts):
                    key = "/".join(key_parts)
                    by_full[key] = row
                source = str(row.get("sourceMod") or "Terraria").lower()
                internal = str(row.get("internalName") or "").lower()
                if internal:
                    by_full[f"{source}/{internal}"] = row
                    by_full.setdefault(internal, row)
                name = str(row.get("name") or row.get("Name") or "").strip().lower()
                if name:
                    by_full.setdefault(name, row)
    except Exception as e:
        print(f"[InfiniCrafterLocal] runtime dump load failed for {path}: {e!r}")
    return rows, by_type, by_full


def runtime_item_lookup(
    item: dict[str, Any],
    by_type: dict[Any, dict[str, Any]],
    by_name: dict[str, dict[str, Any]],
    *,
    item_field: Callable[[dict[str, Any], str, Any], Any],
) -> dict[str, Any]:
    t = item_field(item, "type", None)
    if t is not None:
        try:
            found = by_type.get(int(t))
            if isinstance(found, dict):
                return found
        except Exception:
            pass
    source = str(item_field(item, "sourceMod", "Terraria") or "Terraria").lower()
    internal = str(item_field(item, "internalName", "") or "").lower()
    return by_name.get(f"{source}/{internal}") or by_name.get(internal) or {}


def runtime_projectile_lookup(type_id: Any, by_type: dict[Any, dict[str, Any]]) -> dict[str, Any]:
    try:
        found = by_type.get(int(type_id))
        if isinstance(found, dict):
            return found
    except Exception:
        pass
    return {}
