from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any


def sanitize_image_prompt_background(text: Any) -> str:
    """Use chroma/magenta key prompts instead of asking the image model for alpha.

    Alpha is produced by local postprocess, not by SD/Z-Image. This prevents models from
    drawing checkerboards or fake transparent previews.
    """
    s = str(text or "")
    if not s:
        return ""
    replacements = [
        (r"transparent[- ]background", "solid magenta key background"),
        (r"transparent background", "solid magenta key background"),
        (r"transparent", "solid magenta key"),
        (r"alpha background", "solid magenta key background"),
        (r"checkerboard", "solid magenta key"),
    ]
    for pat, repl in replacements:
        s = re.sub(pat, repl, s, flags=re.IGNORECASE)
    return s

def sprite_status_from_raw_path(path: str, backend: str, *, invalid: bool = False) -> str:
    """Status must describe the actual source, not just the selected backend.

    SDCPP/ComfyUI/A1111 may fall back to procedural PNGs. Those must not be reported
    as generated by the image model.
    """
    name = Path(str(path or "")).name.lower()
    b = str(backend or "").lower()
    if not path:
        return "failed"
    if "raw_sdcpp" in name or "raw_comfy" in name or "raw_a1111" in name:
        return "generated_warn_invalid" if invalid else "generated"
    if b in {"procedural", "offline", "none"}:
        return "fallback"
    if name.endswith("_raw.png") or "_procedural" in name:
        return "fallback_after_failed_generation" if b not in {"procedural", "offline", "none"} else "fallback"
    return "generated_warn_invalid" if invalid and b not in {"procedural", "offline", "none"} else ("fallback" if b in {"procedural", "offline", "none"} else "generated")

def strip_sprite_resolution_tokens(text: str) -> str:
    """Remove final sprite-size instructions from prompts sent to image models.

    The generator renders a large canvas and the pipeline crops/downscales later;
    telling Z-Image that the subject is "16x16" or "32x32 resolution" fights the
    fill/crop contract and produces tiny blobs.  Keep pixel-art style, drop size.
    """
    t = str(text or "")
    t = re.sub(r"(?i)\b\d{1,3}\s*[x×]\s*\d{1,3}\s*(?:px|pixel[- ]art|pixel(?:s)?|resolution|sprite|icon)?\b", "pixel art", t)
    t = re.sub(r"(?i)\b(?:at|in|with)\s+\d{1,3}\s*[x×]\s*\d{1,3}\s*(?:px|pixel(?:s)?|resolution)?\b", "", t)
    t = re.sub(r"(?i)\b(?:tiny|small|large)?\s*(?:\d{1,3}\s*px)\s+(?:resolution|canvas|sprite|icon)\b", "", t)
    t = re.sub(r"(?i)\b(?:low|high)?\s*resolution\b", "", t)
    t = re.sub(r"(?i)\b(?:canvas|sprite|icon)\s+size\s*[:=]?\s*\d{1,3}\b", "", t)
    t = re.sub(r"(?i)\bpixel art\s*,?\s*art\b", "pixel art", t)
    t = re.sub(r"(?i)\bpixel art\s*,\s*pixel art\b", "pixel art", t)
    t = re.sub(r"(?i)\bpixel art\s+pixel art\b", "pixel art", t)
    return re.sub(r"\s+", " ", t).strip(" ,.;")


def zimage_pe_clean_text(text: str) -> str:
    """Collapse SD-style boilerplate into a plain final-description prompt.

    Z-Image Turbo's public prompt-expander rewrites a concise subject description
    into the final visual instruction.  It does not benefit from A1111-style
    prompt cargo such as negative-prompt blocks, quality-tag spam, or runtime
    implementation notes.  Strip those residues and keep only the concrete image
    description.
    """
    t = strip_sprite_resolution_tokens(str(text or ""))
    # Remove explicit negative-prompt sections wholesale before token cleanup so lists like
    # "negative prompt: watermark, text, blurry, ..." do not leak back into the positive prompt.
    t = re.sub(r"(?is)(?:^|[.;,]\s*)(?:negative prompt|negative)\s*:\s*.*$", "", t)
    # Some frontends inline avoid/undesired blocks instead of a separate negative field.
    t = re.sub(r"(?is)(?:^|[.;,]\s*)(?:avoid|undesired|do not include)\s*:\s*(?:watermark|text|logo|blurry|lowres|low resolution|worst quality|bad anatomy|signature|jpeg artifacts)(?:[^.]*)(?:$|\.)", ".", t)
    replacements = [
        (r"\bZ[- ]Image prompt\b[:,]?", ""),
        (r"\bprompt\s*:\s*", ""),
        (r"\bdrawing instruction[s]?\b[:,]?", ""),
        (r"\basset role:\s*\w+\b", ""),
        (r"\bitem fantasy:\s*", "It visually reads as "),
        # Common SD/A1111 boilerplate that adds no concrete visual information for Z-Image.
        (r"\bmasterpiece\b[:,]?", ""),
        (r"\bbest quality\b[:,]?", ""),
        (r"\bhigh quality\b[:,]?", ""),
        (r"\bultra[- ]detailed\b[:,]?", ""),
        (r"\bhighly detailed\b[:,]?", ""),
        (r"\bextremely detailed\b[:,]?", ""),
        (r"\babsurdres\b[:,]?", ""),
        (r"\b8k\b[:,]?", ""),
        (r"\b4k\b[:,]?", ""),
        (r"\blowres\b[:,]?", ""),
        (r"\blow resolution\b[:,]?", ""),
        (r"\blow quality\b[:,]?", ""),
        (r"\bworse quality\b[:,]?", ""),
        (r"\bworst quality\b[:,]?", ""),
        (r"\bbad anatomy\b[:,]?", ""),
        (r"\bjpeg artifacts\b[:,]?", ""),
        (r"\bsignature\b[:,]?", ""),
        (r"\bwatermark\b[:,]?", ""),
        (r"\bno watermark\b[:,]?", ""),
        (r"\bno text(?:\s*,\s*letters\s*,\s*logos\s*,\s*or\s*UI marks)?\b[:,]?", "without letters, logos, or UI marks"),
        (r"\btext[- ]free\b", "without letters, logos, or UI marks"),
        (r"\bpixel perfect\b[:,]?", "crisp pixel-art"),
        (r"\bcentered composition\b[:,]?", ""),
        (r"\bsingle sprite sheet\b[:,]?", "single sprite"),
        # Runtime / engine phrasing -> concrete visual phrasing.
        (r"\bcode handles shot count/spread/splits, do not draw multiple arrows inside one PNG\b", "the visible texture shows one projectile body"),
        (r"\bruntime code handles\b", "the visible texture keeps"),
        (r"\bcode handles\b", "the visible texture keeps"),
        (r"\bfor runtime rotation\b", "along its length"),
        (r"\bruntime/VFX draws the long tether\b", "the visible sprite includes a short local tether detail only when it improves readability"),
        (r"\bprojectile PNG is the compact harpoon head/hook/anchor/blade body only\b", "the visible projectile body is a compact harpoon head, hook, anchor, or blade"),
        (r"\blong rope/chain/tether is not part of the PNG\b", "visible rope or chain stays as a short local attachment when present"),
        (r"\bno full-length spear shaft, no polearm handle, no line crossing the canvas, no off-canvas cord; allow only a tiny rope stump, short chain nub, small loop, or compact coil attached to the body\b", "any rope or chain detail is a short local attachment that supports the main silhouette"),
        (r"\bnot a held polearm animation\b", "in a free-flying projectile pose"),
        (r"\bnot a free-flying bolt\b", "in a held projection pose"),
        (r"\bno player hand, no full melee swing pose\b", "show only the projectile body"),
        (r"\bwith no huge empty border\b", "while keeping the subject large in frame"),
        (r"\bno full[- ]canvas trail\b", "with only a short local trail accent"),
        (r"\bno full[- ]canvas chains?\b", "with only compact local chain detail when it belongs to the subject"),
        (r"\bno full[- ]screen cord\b", "with only compact local cord detail when it belongs to the subject"),
        (r"\bno oversized empty icon\b", "with the subject kept large in frame"),
        (r"\bno magic glow\b", "without magical glow"),
        (r"\bno coin silhouette\b", "without a coin silhouette"),
        (r"\bno readable letters, numbers, logo marks, UI labels, or symbols\b", "without text, logos, or UI marks"),
        (r"\bzero readable letters, numbers, logo marks, UI labels, or symbols\b", "without text, logos, or UI marks"),
        (r"\bstring/tether is runtime/VFX, not in the PNG\b", "the visible yoyo string, if shown, is only a short local nub"),
        (r"\bfull whip arc/cord is runtime/VFX, not in the PNG\b", "the visible whip form is a compact tip or short segment"),
    ]
    for pat, repl in replacements:
        t = re.sub(pat, repl, t, flags=re.IGNORECASE)
    # Remove leftover comma-soup fragments from stripped SD boilerplate.
    t = re.sub(r"(?i)(?:^|[\s,;])(?:watermark|signature|logo|text|blurry|lowres|low resolution|worst quality|bad anatomy|jpeg artifacts)(?=$|[\s,;])", " ", t)
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"\s*,\s*,+", ", ", t)
    t = re.sub(r"\s*\.\s*\.\s*", ". ", t)
    t = re.sub(r"\s*[,;]\s*(?:[,;]\s*)+", ", ", t)
    t = re.sub(r"(?:^|[.;])\s*(?:,\s*)+", ". ", t)
    t = re.sub(r"\s+", " ", t).strip(" ,.;")
    return t

def truncate_prompt_at_boundary(text: str, limit: int) -> str:
    """Trim prompt text without leaving a broken word or half instruction."""
    value = re.sub(r"\s+", " ", str(text or "")).strip(" ,.;")
    if limit <= 0:
        return ""
    if len(value) <= limit:
        return value
    window = value[:limit + 1]
    minimum = max(24, int(limit * 0.55))
    cut = -1
    for separator in (". ", "; ", ", ", " "):
        candidate = window.rfind(separator)
        if candidate >= minimum:
            cut = candidate + (1 if separator != " " else 0)
            break
    if cut < 0:
        cut = limit
    return value[:cut].rstrip(" ,.;")


def compact_prompt_parts(parts: list[str], *, limit: int, separator: str = ", ") -> str:
    """Join prompt parts with exact de-duplication and a reserved final guard."""
    cleaned: list[str] = []
    seen: set[str] = set()
    for raw in parts:
        value = re.sub(r"\s+", " ", str(raw or "")).strip(" ,.;")
        if not value:
            continue
        key = value.casefold()
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(value)
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return truncate_prompt_at_boundary(cleaned[0], limit)
    guard = cleaned[-1]
    guard_budget = min(len(guard), max(120, limit // 2))
    guard = truncate_prompt_at_boundary(guard, guard_budget)
    body_budget = max(1, limit - len(guard) - len(separator))
    body = truncate_prompt_at_boundary(separator.join(cleaned[:-1]), body_budget)
    return separator.join(part for part in (body, guard) if part)


def compact_zimage_asset_prompt(parts: list[str], role: str, limit: int = 1800) -> str:
    """Build a subject-first prompt while preserving the final technical guard.

    Character slicing used to cut prompts mid-sentence and could remove the chroma/one-
    subject guard entirely. The last part is the caller-owned technical guard; reserve it
    and compact only the descriptive body. No item semantics are added here.
    """
    cleaned: list[str] = []
    seen: set[str] = set()
    for raw in parts:
        t = zimage_pe_clean_text(re.sub(r"\s+", " ", str(raw or "")).strip(" ,.;"))
        if not t:
            continue
        key = re.sub(r"\s+", " ", t.lower())
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(t)
    if not cleaned:
        cleaned.append(f"A single Terraria-like {role} pixel sprite on a uniform #ff00ff magenta chroma-key canvas")

    if len(cleaned) == 1:
        return truncate_prompt_at_boundary(cleaned[0], max(1, limit - 1)).rstrip(".") + "."

    guard = cleaned[-1].rstrip(".")
    reserved = min(len(guard), max(120, limit // 2))
    if len(guard) > reserved:
        guard = truncate_prompt_at_boundary(guard, reserved)
    body_limit = max(1, limit - len(guard) - 3)
    body = truncate_prompt_at_boundary(". ".join(cleaned[:-1]), body_limit)
    prompt = ". ".join(part for part in (body, guard) if part).strip(" .")
    return prompt + "."


_CONFLICTING_SPRITE_WRAPPER_PATTERNS = tuple(
    re.compile(pattern, re.IGNORECASE)
    for pattern in (
        r"\b(?:dark|black|white|blue|plain|solid|textured)\s+background\b",
        r"\bbackground\b",
        r"\bbackdrop\b",
        r"\bvignette\b",
        r"\batmospheric\s+(?:scene|background|backdrop)\b",
        r"\b(?:full|wide|environmental|room|landscape|action)\s+scene\b",
        r"\bscene\s+background\b",
        r"\bon\s+(?:a|the)\s+pedestal\b",
        r"\bcharacter\s+holding\b",
        r"\b(?:human|character|player)\s+hands?\b",
        r"\bhands?\s+holding\b",
        r"\bheld\s+in\s+(?:a|two|the)\s+hands?\b",
        r"\bui\s+frame\b",
        r"\b(?:no|without)\s+text\b",
        r"\btext[- ]free\b",
        r"\bwatermark\b",
    )
)



def _has_conflicting_sprite_wrapper(text: str) -> bool:
    return any(pattern.search(str(text or "")) for pattern in _CONFLICTING_SPRITE_WRAPPER_PATTERNS)


def strip_conflicting_sprite_prompt_bits(text: str) -> str:
    text = strip_sprite_resolution_tokens(str(text or "")).strip()
    if not text:
        return ""
    cleaned_parts = []
    for raw_part in text.replace(";", ",").split(","):
        part = raw_part.strip()
        if not part:
            continue
        if _has_conflicting_sprite_wrapper(part):
            # Visual Director often writes wrappers like:
            # "single pixel-art icon on solid magenta key background (#ff00ff):
            # two silver shurikens ...". Keep a clean post-colon subject. Word-boundary
            # matching is intentional: old substring checks treated ``texture`` as
            # forbidden ``text`` and ``grounded`` as forbidden ``ground``.
            if ":" in part:
                tail = part.split(":", 1)[1].strip(" ,.;")
                if tail and not _has_conflicting_sprite_wrapper(tail):
                    cleaned_parts.append(tail)
            continue
        cleaned_parts.append(part)
    cleaned = ", ".join(cleaned_parts)
    return truncate_prompt_at_boundary(cleaned, 1400)

def sanitize_projectile_prompt_multiplicity(prompt: str, *, force_single: bool = False) -> str:
    """Keep executable multiplicity out of a single projectile texture.

    The generic cleanup handles common accidental duplicates. ``force_single`` is
    enabled only from explicit runtime shot/split counts and is disabled for an
    explicitly authored bundle/cluster/swarm projectile family.  No weapon names
    or tooltip prose select this policy.
    """
    p = str(prompt or "")
    replacements = [
        (r"\btwo\s+small\s+arrow\s+sprites\b", "one small arrow sprite"),
        (r"\btwo\s+arrow\s+sprites\b", "one arrow sprite"),
        (r"\btwo\s+arrows\b", "one arrow"),
        (r"\btwin\s+arrows\b", "one twin-themed arrow"),
        (r"\bpair\s+of\s+arrows\b", "one arrow"),
        (r"\bV-formation\b", "side-view"),
        (r"\bV\s+formation\b", "side-view"),
        (r"\bspread\s+of\s+two\b", "single"),
        (r"\btwo\s+projectiles\b", "one projectile"),
    ]
    if force_single:
        count = r"(?:two|three|four|five|six|seven|eight|[2-8])"
        body = r"(?:projectiles?|arrows?|bullets?|pellets?|rockets?|darts?|bolts?|shards?|stars?|needles?|orbs?|discs?|blades?)"
        replacements.extend([
            (rf"\b(?:a\s+)?(?:spread|fan|volley|cluster|group)\s+of\s+{count}\s+{body}\b", "one projectile body"),
            (rf"\b{count}\s+{body}\b", "one projectile body"),
            (rf"\bmultiple\s+{body}\b", "one projectile body"),
        ])
    for pat, repl in replacements:
        p = re.sub(pat, repl, p, flags=re.IGNORECASE)
    return re.sub(r"\s+", " ", p).strip()

def visual_palette_entry_is_chroma_key_noise(value: str) -> bool:
    """Remove background/key colors from foreground material palettes only.

    Bare `magenta` is overwhelmingly the #ff00ff key leaking from the visual
    director. Descriptive foreground colors like `magenta crystal` are preserved.
    """
    lo = re.sub(r"\s+", " ", str(value or "").strip().lower())
    if not lo:
        return True
    if any(tok in lo for tok in ["magenta key", "solid magenta", "chroma", "#ff00ff", "background", "canvas"]):
        return True
    return lo in {"magenta", "pure magenta", "flat magenta", "fuchsia", "hot pink", "key magenta"}

def sanitize_visual_palette(values: Any, limit: int = 8) -> list[str]:
    if isinstance(values, str):
        raw_values = [x.strip() for x in re.split(r"[,;/]", values) if x.strip()]
    elif isinstance(values, (list, tuple)):
        raw_values = [str(x).strip() for x in values if str(x).strip()]
    else:
        raw_values = []
    out: list[str] = []
    seen: set[str] = set()
    for raw in raw_values:
        if visual_palette_entry_is_chroma_key_noise(raw):
            continue
        cleaned = zimage_pe_clean_text(raw)
        if not cleaned or visual_palette_entry_is_chroma_key_noise(cleaned):
            continue
        key = cleaned.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(cleaned)
        if len(out) >= limit:
            break
    return out

def zimage_palette_sentence(palette_words: str) -> str:
    cleaned_palette = sanitize_visual_palette(palette_words, limit=8)
    if cleaned_palette:
        return f"Color scheme and materials: {', '.join(cleaned_palette)}."
    return "Color scheme and materials: limited high-contrast Terraria-like pixel palette."

def zimage_text_policy_sentence(data: dict[str, Any]) -> str:
    """Preserve authored text only when the item explicitly contains text.

    PE.py is strict about text. Most Terraria item/projectile sprites should contain
    no letters; if the authored prompt includes quoted text, keep it exactly.
    """
    chunks: list[str] = []
    for key in ("name", "tooltip"):
        chunks.append(str(data.get(key) or ""))
    visual = data.get("visual") if isinstance(data.get("visual"), dict) else {}
    for key in ("imagePrompt", "projectileImagePrompt", "impactImagePrompt", "childImagePrompt", "fieldImagePrompt"):
        chunks.append(str(visual.get(key) or ""))
    quoted = []
    for raw in chunks:
        quoted.extend(re.findall(r'"([^"]{1,40})"', raw))
    if quoted:
        exact = "; ".join(dict.fromkeys(quoted))[:180]
        return f"Any visible text is copied exactly as: {exact}."
    return "without letters, logos, or UI marks."

# -----------------------------------------------------------------------------
# Procedural visual fallback used when AI image generation is disabled/unavailable
# -----------------------------------------------------------------------------

def _stable_rgb(seed: str) -> tuple[int, int, int]:
    h = hashlib.sha256(seed.encode("utf-8", "ignore")).digest()
    return (80 + h[0] % 150, 80 + h[1] % 150, 80 + h[2] % 150)


def generate_procedural_asset(
    data: dict[str, Any],
    role: str,
    *,
    variant: int = 0,
    canvas_size: int = 32,
    sprite_dir: Path,
    image_cls: Any,
    image_draw_cls: Any,
) -> str:
    role = str(role or "projectile").lower()
    canvas = int(canvas_size or 32)
    canvas = max(16, min(96, canvas))
    sprite_dir.mkdir(parents=True, exist_ok=True)
    seed = f"{data.get('id') or data.get('name') or 'item'}:{role}:{variant}"
    color = _stable_rgb(seed)
    accent = _stable_rgb(seed + ":accent")
    img = image_cls.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    d = image_draw_cls.Draw(img)
    pad = max(3, canvas // 8)
    cx = canvas // 2
    cy = canvas // 2
    if role == "impact":
        d.ellipse([pad, pad, canvas - pad, canvas - pad], fill=(*accent, 210))
        d.ellipse([pad * 2, pad * 2, canvas - pad * 2, canvas - pad * 2], fill=(255, 255, 255, 230))
    elif role == "child":
        r = max(2, canvas // 6)
        d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(*color, 235))
        d.line([cx - r * 2, cy, cx + r * 2, cy], fill=(*accent, 180), width=max(1, canvas // 16))
    elif role == "field":
        d.ellipse([pad, pad, canvas - pad, canvas - pad], outline=(*color, 230), width=max(2, canvas // 10))
        d.ellipse([pad * 2, pad * 2, canvas - pad * 2, canvas - pad * 2], outline=(*accent, 180), width=max(1, canvas // 16))
    elif role == "item":
        d.rounded_rectangle([pad, pad, canvas - pad, canvas - pad], radius=max(3, canvas // 6), fill=(*color, 235))
        d.line([pad * 2, canvas - pad * 2, canvas - pad * 2, pad * 2], fill=(*accent, 240), width=max(2, canvas // 10))
    else:
        d.polygon([(pad, cy), (canvas - pad, pad), (canvas - pad * 2, cy), (canvas - pad, canvas - pad)], fill=(*color, 240))
        d.line([pad, cy, canvas - pad, cy], fill=(*accent, 220), width=max(2, canvas // 12))
    name = f"{str(data.get('id') or 'generated')}_{role}_{variant}_{canvas}_procedural.png"
    safe = re.sub(r"[^a-zA-Z0-9_.-]+", "_", name)[:120]
    path = sprite_dir / safe
    img.save(path)
    return str(path)


def generate_procedural_sprite(data: dict[str, Any], *, variant: int = 0, sprite_dir: Path, image_cls: Any, image_draw_cls: Any) -> str:
    canvas = int(((data.get("visual") or {}).get("preferredCanvasSize") or 32) if isinstance(data.get("visual"), dict) else 32)
    return generate_procedural_asset(data, "item", variant=variant, canvas_size=canvas, sprite_dir=sprite_dir, image_cls=image_cls, image_draw_cls=image_draw_cls)
