from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


# AGENT MAP: static settings schema for the desktop GUI.
# Owns field order, defaults, presets, and user-facing help text. GUI widgets and
# process/network actions stay in settings_gui.py.

FIELD_ORDER = [
    "INFINI_USE_LLM",
    "INFINI_LLM_RUNTIME_AUTHORING",
    "INFINI_LLM_RUNTIME_PLAN_REQUIRED",
    "INFINI_LLM_RUNTIME_STRICT_VALIDATION",
    "INFINI_BALANCE_MODE",
    "INFINI_ALLOW_DETERMINISTIC_DEV_FALLBACK",
    "INFINI_GUI_PIPELINE_PRESET",
    "INFINI_LLM_PROVIDER",
    "INFINI_LMSTUDIO_URL",
    "INFINI_LMSTUDIO_MODEL",
    "INFINI_OPENROUTER_API_KEY",
    "INFINI_OPENROUTER_MODEL",
    "INFINI_OPENROUTER_HTTP_REFERER",
    "INFINI_OPENROUTER_APP_TITLE",
    "INFINI_OPENAI_COMPAT_BASE_URL",
    "INFINI_OPENAI_COMPAT_API_KEY",
    "INFINI_OPENAI_COMPAT_MODEL",
    "INFINI_LLM_FALLBACK_PROVIDER",
    "INFINI_LLM_FALLBACK_MODEL",
    "INFINI_LLM_FALLBACK_BASE_URL",
    "INFINI_LLM_FALLBACK_API_KEY",
    "INFINI_LLM_FALLBACK_NETWORK_FAILS",
    "INFINI_LLM_RESPONSE_FORMAT",
    "INFINI_LLM_TEMPERATURE",
    "INFINI_VISUAL_DIRECTOR_TEMPERATURE",
    "INFINI_LLM_MAX_TOKENS",
    "INFINI_LLM_REASONING_MODE",
    "INFINI_LLM_REASONING_MAX_TOKENS",
    "INFINI_LLM_REASONING_EXCLUDE",
    "INFINI_LLM_LOCAL_REASONING_PROMPT",
    "INFINI_IMAGE_BACKEND",
    "INFINI_SDCPP_SERVER_EXE",
    "INFINI_SDCPP_ROCM_COMPAT_ROOT",
    "INFINI_SDCPP_MODEL",
    "INFINI_SDCPP_VAE",
    "INFINI_SDCPP_LLM",
    "INFINI_SDCPP_LORA_DIR",
    "INFINI_SDCPP_LORA_FILE",
    "INFINI_SDCPP_LORA_WEIGHT",
    "INFINI_SDCPP_LORA_PROMPT_TAGS",
    "INFINI_SDCPP_SERVER_URL",
    "INFINI_SDCPP_SERVER_AUTOSTART",
    "INFINI_SDCPP_SERVER_COMMAND_MODE",
    "INFINI_SDCPP_SERVER_COMMAND_TEMPLATE",
    "INFINI_SDCPP_SERVER_EXTRA_ARGS",
    "INFINI_SDCPP_SERVER_SHOW_CONSOLE",
    "INFINI_SDCPP_SERVER_LOG_FILE",
    "INFINI_SDCPP_WIDTH",
    "INFINI_SDCPP_HEIGHT",
    "INFINI_SDCPP_STEPS",
    "INFINI_SDCPP_CFG",
    "INFINI_SDCPP_SAMPLER",
    "INFINI_SDCPP_SEED",
    "INFINI_ZIMAGE_PROMPT_CONTRACT",
    "INFINI_ZIMAGE_POSITIVE_ONLY",
    "INFINI_IMAGE_API_BASE_URL",
    "INFINI_IMAGE_API_KEY",
    "INFINI_IMAGE_API_MODEL",
    "INFINI_IMAGE_API_PATH",
    "INFINI_IMAGE_API_SIZE",
    "INFINI_IMAGE_API_TIMEOUT",
    "INFINI_A1111_URL",
    "INFINI_COMFYUI_URL",
    "INFINI_VISUAL_ASSET_MODE",
    "INFINI_VISUAL_DIRECTOR_LLM",
    "INFINI_VISUAL_DIRECTOR_MAX_TOKENS",
    "INFINI_VISUAL_GENERATE_PROJECTILE_IMAGES",
    "INFINI_VISUAL_GENERATE_IMPACT_IMAGES",
    "INFINI_VISUAL_GENERATE_CHILD_FIELD_IMAGES",
    "INFINI_VFX_LLM_DIRECTOR",
    "INFINI_REMOVE_BG",
    "INFINI_BG_REMOVE_MODE",
    "INFINI_BG_COLOR",
    "INFINI_CHROMA_TOLERANCE",
    "INFINI_ALPHA_THRESHOLD",
    "INFINI_SPRITE_KEYER_SPILL_RADIUS",
    "INFINI_SPRITE_KEYER_RESIDUE_STEPS",
    "INFINI_SPRITE_RETRIES",
    "INFINI_SAVE_SPRITE_STAGES",
    "INFINI_PIXEL_POSTERIZE",
    "INFINI_MAX_COLORS",
    "INFINI_SPRITE_PROCESSING_PROFILE",
    "INFINI_SPRITE_MASTER_CANVAS",
    "INFINI_SPRITE_DOWNSCALE_FILTER",
    "INFINI_SPRITE_CHROMA_DEFRINGE",
    "INFINI_SPRITE_PREMULTIPLIED_RESIZE",
    "INFINI_VISUAL_STRICT_AI_AUTHORSHIP",
    "INFINI_VISUAL_ALLOW_PROCEDURAL_FALLBACK",
    "INFINI_HOST",
    "INFINI_PORT",
    "INFINI_ASSET_PUBLIC_BASE_URL",
    "INFINI_TERRARIA_PORT",
    "INFINI_CRAFT_HTTP_TIMEOUT_SECONDS",
    "INFINI_CRAFT_HTTP_ATTEMPTS",
    "INFINI_TRACE_PROMPTS",
    "INFINI_TRACE_MAX_PROMPT_CHARS",
    "INFINI_TRACE_EVENTS_TAIL",
]

SDCPP_DEFAULT_COMMAND_TEMPLATE = "{exe} --diffusion-model {model} -l {host} --listen-port {port} -W {width} -H {height} --steps {steps} --cfg-scale {cfg} --sampling-method {sampler} {extra}"

SDCPP_EXTRA_PROFILES = {
    # Official sd.cpp backend syntax allows per-module runtime placement such as
    # diffusion=vulkan0,vae=cpu,te=vulkan0. If --params-backend is omitted,
    # sd.cpp stores parameters on the same backend as that module runtime unless
    # a measured split intentionally keeps selected weights elsewhere. Keep model,
    # VAE, Qwen/LLM and LoRA paths in dedicated GUI rows; these profiles are only
    # runtime/performance flags.
    "flux2_klein4b_rx6800xt_hybrid": "-v --backend diffusion=rocm0,vae=vulkan0,te=rocm0 --params-backend te=cpu --rng cuda --flow-shift 3 --eager-load --diffusion-conv-direct --vae-conv-direct",
    "zimage_amd_safe": "-v --backend diffusion=vulkan0,vae=vulkan0,te=vulkan0 --params-backend te=cpu --rng cuda --flow-shift 3 --eager-load --diffusion-conv-direct --vae-conv-direct",
    "zimage_amd_low_vram": "-v --backend diffusion=vulkan0,vae=cpu,te=cpu --rng cuda --flow-shift 3",
    "zimage_amd_full_gpu": "-v --backend diffusion=vulkan0,vae=vulkan0,te=vulkan0 --rng cuda --flow-shift 3 --eager-load --diffusion-conv-direct --vae-conv-direct",
    "zimage_amd_disk_params": "-v --backend diffusion=vulkan0,vae=vulkan0,te=vulkan0 --params-backend te=disk --rng cuda --flow-shift 3 --eager-load --diffusion-conv-direct --vae-conv-direct",
    "zimage_cpu_compat": "-v --backend cpu --rng cpu --flow-shift 3",
    "compat_offload": "-v --offload-to-cpu --flow-shift 3",
    "basic_verbose": "-v --flow-shift 3",
    "vulkan_te_vae_cpu_dbcache": "-v --backend diffusion=vulkan0,vae=vulkan0,te=vulkan0 --params-backend te=cpu --rng cuda --flow-shift 3 --eager-load --diffusion-conv-direct --vae-conv-direct --cache-mode dbcache --cache-option \"threshold=0.08,warmup=2\"",
}

SDCPP_EXTRA_PROFILE_HELP = {
    "flux2_klein4b_rx6800xt_hybrid": "FLUX.2 Klein 4B winner для RX 6800 XT: TE compute и diffusion на ROCm, VAE на Vulkan, параметры TE в CPU RAM. Soak20: mean 3.408s, p95 3.441s; game-load не проверялся.",
    "zimage_amd_safe": "AMD safe — измеренный профиль RX 6800 XT: runtime diffusion/VAE/TE на Vulkan, параметры Qwen/TE в RAM, direct convolution включён. Почти full-GPU скорость при заметно меньшей постоянной VRAM.",
    "zimage_amd_low_vram": "AMD low VRAM — diffusion на Vulkan, VAE и Qwen/TE на CPU. Меньше VRAM-пиков, но condition/Qwen может быть медленнее.",
    "zimage_amd_full_gpu": "AMD full GPU — runtime и параметры diffusion/VAE/Qwen на Vulkan, оба direct convolution включены. Самый быстрый измеренный Z-Image профиль, но держит больше VRAM.",
    "zimage_amd_disk_params": "Disk params — runtime как AMD safe, но параметры Qwen/TE перечитываются с диска по необходимости. Экономит RAM/VRAM, но добавляет загрузку на каждый запрос.",
    "zimage_cpu_compat": "CPU compat — всё на CPU. Очень медленно, зато полезно проверить, что пути/модели/команда живые без Vulkan.",
    "compat_offload": "Compat offload — старый совместимый --offload-to-cpu. Оставлен для сборок/форков, где новые --backend/--params-backend работают странно.",
    "vulkan_te_vae_cpu_dbcache": "DBCache split — измеренный AMD safe + dbcache. Эксперимент; на FLUX.2 Klein 4-step был медленнее, при артефактах/мыле отключить cache.",
    "basic_verbose": "Basic — только verbose + flow-shift. Для ручных экспериментов, когда backend-флаги прописываешь сам.",
}


SDCPP_EXTRA_FLAG_SPECS = [
    ("Verbose", "-v", "Показывает подробный лог sd.cpp: backend, загрузку весов, время sampling/decode и причины падений."),
    ("Diffusion FA", "--diffusion-fa", "Flash Attention для diffusion-графа. Может снизить память; поддержка зависит от модели/backend/сборки."),
    ("VAE direct", "--vae-conv-direct", "Direct convolution для VAE. Экспериментальная оптимизация; если decode ломается — убрать."),
    ("Diff direct", "--diffusion-conv-direct", "Direct convolution для diffusion. Эксперимент; оставлять только если сборка/модель реально принимает флаг."),
    ("RNG GPU", "--rng cuda", "Генератор случайности как в webui/GPU RNG. Дефолтный вариант sd.cpp для воспроизводимости с webui-стилем."),
    ("RNG CPU", "--rng cpu", "CPU/ComfyUI-style RNG. Полезно, если хочешь ближе к ComfyUI или стабильнее сравнивать backend'и."),
    ("Flow 2", "--flow-shift 2", "Flow shift 2: сдвиг расписания timestep для Flow/DiT моделей. Чуть меньше смещает шум к поздним шагам: может давать мягче/чище, но иногда слабее детали/контраст."),
    ("Flow 3", "--flow-shift 3", "Flow shift 3: более сильный flow-shift; для Z-Image в sd.cpp обычно рабочий дефолт. Часто контрастнее/резче, но может пережигать или усиливать артефакты."),
    ("LoRA runtime", "--lora-apply-mode at_runtime", "LoRA применяется во время инференса. Лучше совместимость/точность для quantized/GGUF, но может быть медленнее."),
    ("LoRA auto", "--lora-apply-mode auto", "Дать sd.cpp самому выбрать режим LoRA: для quantized весов обычно at_runtime, иначе immediately."),
    ("Cache DBCache", "--cache-mode dbcache --cache-option \"threshold=0.08,warmup=2\"", "DiT/Z-Image cache: может ускорить повторяемые прогонки, но при артефактах/мыле отключить."),
    ("Params disk", "--params-backend disk", "Минимальная RAM/VRAM-резидентность: веса перечитываются с диска по мере нужды. Может быть медленно."),
]


def repair_sdcpp_command_template(template: str) -> tuple[str, bool, str]:
    raw = str(template or "").strip()
    if not raw:
        return SDCPP_DEFAULT_COMMAND_TEMPLATE, True, "empty_template"
    required = ("{exe}", "{model}", "{host}", "{port}", "{width}", "{height}", "{steps}", "{cfg}", "{sampler}", "{extra}")
    lowered = raw.lower()
    preset_bleed = any(x in lowered for x in ("openrouter + local", "lm studio + local", "z-image/sd.cppethod"))
    broken_sampling = "--sampling-method" not in raw and "sampling-m" in raw
    missing_required = any(tok not in raw for tok in required)
    if preset_bleed or broken_sampling or missing_required:
        reasons = []
        if preset_bleed: reasons.append("pipeline preset text leaked into command")
        if broken_sampling: reasons.append("broken --sampling-method flag")
        if missing_required: reasons.append("missing placeholders")
        return SDCPP_DEFAULT_COMMAND_TEMPLATE, True, "; ".join(reasons)
    return raw, False, ""


DEFAULTS = {
    "INFINI_USE_LLM": "1",
    "INFINI_LLM_RUNTIME_AUTHORING": "1",
    "INFINI_LLM_RUNTIME_PLAN_REQUIRED": "1",
    "INFINI_LLM_RUNTIME_STRICT_VALIDATION": "1",
    "INFINI_BALANCE_MODE": "safety",
    "INFINI_ALLOW_DETERMINISTIC_DEV_FALLBACK": "0",
    "INFINI_GUI_PIPELINE_PRESET": "Локалка: LM Studio + FLUX.2 Klein 4B hybrid",
    "INFINI_LLM_PROVIDER": "local",
    "INFINI_LMSTUDIO_URL": "http://127.0.0.1:1234",
    "INFINI_LMSTUDIO_MODEL": "auto",
    "INFINI_OPENROUTER_API_KEY": "",
    "INFINI_OPENROUTER_MODEL": "auto",
    "INFINI_OPENROUTER_HTTP_REFERER": "https://github.com/InfiniCrafterLocal",
    "INFINI_OPENROUTER_APP_TITLE": "InfiniCrafterLocal",
    "INFINI_OPENAI_COMPAT_BASE_URL": "",
    "INFINI_OPENAI_COMPAT_API_KEY": "",
    "INFINI_OPENAI_COMPAT_MODEL": "auto",
    "INFINI_LLM_FALLBACK_PROVIDER": "",
    "INFINI_LLM_FALLBACK_MODEL": "",
    "INFINI_LLM_FALLBACK_BASE_URL": "",
    "INFINI_LLM_FALLBACK_API_KEY": "",
    "INFINI_LLM_FALLBACK_NETWORK_FAILS": "2",
    "INFINI_LLM_RESPONSE_FORMAT": "auto",
    "INFINI_LLM_TEMPERATURE": "0.38",
    "INFINI_VISUAL_DIRECTOR_TEMPERATURE": "0.42",
    "INFINI_LLM_MAX_TOKENS": "9000",
    "INFINI_LLM_REASONING_MODE": "off",
    "INFINI_LLM_REASONING_MAX_TOKENS": "1500",
    "INFINI_LLM_REASONING_EXCLUDE": "1",
    "INFINI_LLM_LOCAL_REASONING_PROMPT": "1",
    "INFINI_IMAGE_BACKEND": "sdcpp",
    "INFINI_SDCPP_SERVER_EXE": r"C:\Games\sdcpp-hybrid-gfx1030\sd-server.exe",
    "INFINI_SDCPP_ROCM_COMPAT_ROOT": r"C:\Games\sdcpp-hybrid-gfx1030",
    "INFINI_SDCPP_MODEL": r"C:\Games\sdcpp\models\Flux 2 4B\flux-2-klein-4b-Q8_0.gguf",
    "INFINI_SDCPP_VAE": r"C:\Games\sdcpp\models\Flux 2 4B\ae.safetensors",
    "INFINI_SDCPP_LLM": r"C:\Games\sdcpp\models\Flux 2 4B\Qwen3-4B-UD-Q5_K_XL.gguf",
    "INFINI_SDCPP_LORA_DIR": "",
    "INFINI_SDCPP_LORA_FILE": "",
    "INFINI_SDCPP_LORA_WEIGHT": "0.65",
    "INFINI_SDCPP_LORA_PROMPT_TAGS": "",
    "INFINI_SDCPP_SERVER_URL": "http://127.0.0.1:7861",
    "INFINI_SDCPP_SERVER_AUTOSTART": "1",
    "INFINI_SDCPP_SERVER_COMMAND_MODE": "safe_args",
    "INFINI_SDCPP_SERVER_COMMAND_TEMPLATE": SDCPP_DEFAULT_COMMAND_TEMPLATE,
    "INFINI_SDCPP_SERVER_EXTRA_ARGS": SDCPP_EXTRA_PROFILES["flux2_klein4b_rx6800xt_hybrid"],
    "INFINI_SDCPP_SERVER_SHOW_CONSOLE": "1" if os.name == "nt" else "0",
    "INFINI_SDCPP_SERVER_LOG_FILE": str(ROOT / "cache" / "sdcpp_server.log"),
    "INFINI_SDCPP_WIDTH": "512",
    "INFINI_SDCPP_HEIGHT": "512",
    "INFINI_SDCPP_STEPS": "4",
    "INFINI_SDCPP_CFG": "1.0",
    "INFINI_SDCPP_SAMPLER": "euler",
    "INFINI_SDCPP_SEED": "-1",
    "INFINI_ZIMAGE_PROMPT_CONTRACT": "0",
    "INFINI_ZIMAGE_POSITIVE_ONLY": "1",
    "INFINI_IMAGE_API_BASE_URL": "https://api.openai.com/v1",
    "INFINI_IMAGE_API_KEY": "",
    "INFINI_IMAGE_API_MODEL": "gpt-image-1",
    "INFINI_IMAGE_API_PATH": "/images/generations",
    "INFINI_IMAGE_API_SIZE": "512x512",
    "INFINI_IMAGE_API_TIMEOUT": "180",
    "INFINI_A1111_URL": "http://127.0.0.1:7860",
    "INFINI_COMFYUI_URL": "http://127.0.0.1:8188",
    "INFINI_VISUAL_ASSET_MODE": "full",
    "INFINI_VISUAL_DIRECTOR_LLM": "1",
    "INFINI_VISUAL_DIRECTOR_MAX_TOKENS": "",
    "INFINI_VISUAL_GENERATE_PROJECTILE_IMAGES": "1",
    "INFINI_VISUAL_GENERATE_IMPACT_IMAGES": "0",
    "INFINI_VISUAL_GENERATE_CHILD_FIELD_IMAGES": "0",
    "INFINI_VFX_LLM_DIRECTOR": "1",
    "INFINI_REMOVE_BG": "1",
    "INFINI_BG_REMOVE_MODE": "sprite_keyer",
    "INFINI_BG_COLOR": "magenta",
    "INFINI_CHROMA_TOLERANCE": "34",
    "INFINI_ALPHA_THRESHOLD": "28",
    "INFINI_SPRITE_KEYER_SPILL_RADIUS": "3",
    "INFINI_SPRITE_KEYER_RESIDUE_STEPS": "8",
    "INFINI_SPRITE_RETRIES": "1",
    "INFINI_SAVE_SPRITE_STAGES": "0",
    "INFINI_PIXEL_POSTERIZE": "1",
    "INFINI_MAX_COLORS": "32",
    "INFINI_SPRITE_PROCESSING_PROFILE": "master_soft",
    "INFINI_SPRITE_MASTER_CANVAS": "256",
    "INFINI_SPRITE_DOWNSCALE_FILTER": "box",
    "INFINI_SPRITE_CHROMA_DEFRINGE": "1",
    "INFINI_SPRITE_PREMULTIPLIED_RESIZE": "1",
    "INFINI_VISUAL_STRICT_AI_AUTHORSHIP": "1",
    "INFINI_VISUAL_ALLOW_PROCEDURAL_FALLBACK": "0",
    "INFINI_HOST": "127.0.0.1",
    "INFINI_PORT": "5055",
    "INFINI_ASSET_PUBLIC_BASE_URL": "",
    "INFINI_TERRARIA_PORT": "7777",
    "INFINI_CRAFT_HTTP_TIMEOUT_SECONDS": "240",
    "INFINI_CRAFT_HTTP_ATTEMPTS": "2",
    "INFINI_TRACE_PROMPTS": "1",
    "INFINI_TRACE_MAX_PROMPT_CHARS": "18000",
    "INFINI_TRACE_EVENTS_TAIL": "120",
}

PRESETS = {
    "Локалка: LM Studio + FLUX.2 Klein 4B hybrid": {
        "INFINI_LLM_PROVIDER": "local",
        "INFINI_IMAGE_BACKEND": "sdcpp",
        "INFINI_SDCPP_SERVER_EXE": r"C:\Games\sdcpp-hybrid-gfx1030\sd-server.exe",
        "INFINI_SDCPP_ROCM_COMPAT_ROOT": r"C:\Games\sdcpp-hybrid-gfx1030",
        "INFINI_SDCPP_MODEL": r"C:\Games\sdcpp\models\Flux 2 4B\flux-2-klein-4b-Q8_0.gguf",
        "INFINI_SDCPP_VAE": r"C:\Games\sdcpp\models\Flux 2 4B\ae.safetensors",
        "INFINI_SDCPP_LLM": r"C:\Games\sdcpp\models\Flux 2 4B\Qwen3-4B-UD-Q5_K_XL.gguf",
        "INFINI_SDCPP_LORA_DIR": "",
        "INFINI_SDCPP_LORA_FILE": "",
        "INFINI_SDCPP_LORA_PROMPT_TAGS": "",
        "INFINI_SDCPP_SERVER_AUTOSTART": "1",
        "INFINI_SDCPP_SERVER_COMMAND_MODE": "safe_args",
        "INFINI_SDCPP_SERVER_EXTRA_ARGS": SDCPP_EXTRA_PROFILES["flux2_klein4b_rx6800xt_hybrid"],
        "INFINI_SDCPP_STEPS": "4",
        "INFINI_SDCPP_CFG": "1.0",
        "INFINI_SDCPP_SAMPLER": "euler",
        "INFINI_ZIMAGE_PROMPT_CONTRACT": "0",
        "INFINI_ZIMAGE_POSITIVE_ONLY": "1",
    },
    "Локалка: LM Studio + local Z-Image/sd.cpp": {
        "INFINI_LLM_PROVIDER": "local",
        "INFINI_IMAGE_BACKEND": "sdcpp",
        "INFINI_SDCPP_SERVER_AUTOSTART": "1",
        "INFINI_SDCPP_SERVER_COMMAND_MODE": "safe_args",
        "INFINI_SDCPP_SERVER_EXTRA_ARGS": SDCPP_EXTRA_PROFILES["zimage_amd_safe"],
        "INFINI_SDCPP_STEPS": "8",
        "INFINI_SDCPP_CFG": "1.0",
        "INFINI_SDCPP_SAMPLER": "euler",
    },
    "OpenRouter + local Z-Image/sd.cpp": {
        "INFINI_LLM_PROVIDER": "openrouter",
        "INFINI_IMAGE_BACKEND": "sdcpp",
        "INFINI_SDCPP_SERVER_AUTOSTART": "1",
        "INFINI_SDCPP_SERVER_COMMAND_MODE": "safe_args",
        "INFINI_SDCPP_SERVER_EXTRA_ARGS": SDCPP_EXTRA_PROFILES["zimage_amd_safe"],
        "INFINI_SDCPP_STEPS": "8",
        "INFINI_SDCPP_CFG": "1.0",
        "INFINI_SDCPP_SAMPLER": "euler",
    },
    "OpenRouter + Image API": {
        "INFINI_LLM_PROVIDER": "openrouter",
        "INFINI_IMAGE_BACKEND": "image_api",
        "INFINI_SDCPP_SERVER_AUTOSTART": "0",
    },
    "API LLM only: без картинок": {
        "INFINI_LLM_PROVIDER": "openrouter",
        "INFINI_IMAGE_BACKEND": "off",
        "INFINI_SDCPP_SERVER_AUTOSTART": "0",
    },
}

# Radmin/LAN is intentionally NOT a pipeline preset. It is a network overlay that can be
# applied on top of any LLM/image combination above.


PRESET_HELP = {
    "Локалка: LM Studio + FLUX.2 Klein 4B hybrid": "Основной RX 6800 XT image preset: FLUX.2 Klein 4B, ROCm TE+diffusion, Vulkan VAE, TE weights в CPU RAM; 512x512/4 steps/CFG 1/Euler. Не использует Z-Image LoRA.",
    "Локалка: LM Studio + local Z-Image/sd.cpp": "LLM-контракт пишет локальная модель через LM Studio/OpenAI-compatible API. PNG рисует локальный Z-Image через stable-diffusion.cpp. Это основной офлайн-пайплайн.",
    "OpenRouter + local Z-Image/sd.cpp": "Контракт предмета пишет модель с OpenRouter, а картинки всё равно рисуются локально через Z-Image/sd.cpp. Хороший режим, когда локальная LLM тупит, но VRAM хочется оставить под image gen.",
    "OpenRouter + Image API": "И контракт, и изображения уходят во внешние API. Локальный sd.cpp не нужен и его поля в GUI будут неактивны.",
    "API LLM only: без картинок": "LLM пишет только JSON/механику. Генерация PNG выключена; визуальные и sprite-postprocess поля будут неактивны, потому что обрабатывать нечего.",
}

FIELD_HELP = {
    "INFINI_HOST": "На каком интерфейсе слушает server.py. 127.0.0.1 — только этот ПК; 0.0.0.0 — принимать подключения из LAN/Radmin.",
    "INFINI_PORT": "Порт локального генератора. tModLoader-клиент должен ходить именно сюда.",
    "INFINI_ASSET_PUBLIC_BASE_URL": "Публичный адрес, по которому другие игроки смогут скачать готовые PNG/JSON ассеты с host-ПК. Для Radmin обычно http://26.x.x.x:5055.",
    "INFINI_TERRARIA_PORT": "Порт Terraria/tModLoader сервера для подсказки друзьям. По умолчанию Host & Play/server используют 7777, если ты не менял порт.",
    "INFINI_CRAFT_HTTP_TIMEOUT_SECONDS": "Сколько tModLoader ждёт один HTTP-запрос крафта, прежде чем считать попытку зависшей.",
    "INFINI_CRAFT_HTTP_ATTEMPTS": "Сколько попыток клиент сделает при таймауте/сетевом сбое.",
    "INFINI_TRACE_PROMPTS": "Сохраняет промпты, ответы и шаги pipeline в cache/*.ndjson. Полезно для отладки, но может хранить длинные запросы.",
    "INFINI_TRACE_MAX_PROMPT_CHARS": "Максимум символов промпта/ответа в trace, чтобы лог не разрастался бесконечно.",
    "INFINI_TRACE_EVENTS_TAIL": "Сколько последних событий показывать во вкладке Trace.",
    "INFINI_GUI_PIPELINE_PRESET": "Последний применённый pipeline preset. GUI хранит его в config.env, чтобы после перезапуска открывать тот же режим, а не первый пункт списка.",
    "INFINI_SAVE_SPRITE_STAGES": "Сохранять промежуточные PNG-этапы спрайт-пайплайна (raw, bg_removed, master, final bake) в cache/sprites. Нужен для отладки мастер-канваса и обрезки.",
    "INFINI_CHROMA_TOLERANCE": "Допуск для удаления chroma-key фона. Больше = агрессивнее к магенте, но выше риск задеть полезные edge-пиксели. Обычно 30-40.",
    "INFINI_ALPHA_THRESHOLD": "Порог альфы после вырезания фона. Больше = жестче обрезает полупрозрачные края. Обычно 24-32.",

    "INFINI_LLM_PROVIDER": "Кто пишет JSON-контракт предмета: локальная модель, OpenRouter или другой OpenAI-compatible API.",
    "INFINI_LMSTUDIO_URL": "Адрес локального OpenAI-compatible сервера LM Studio/Ollama. Активен только при LLM provider = local.",
    "INFINI_LMSTUDIO_MODEL": "Имя локальной модели. auto обычно достаточно, если endpoint сам выбирает загруженную модель.",
    "INFINI_OPENROUTER_API_KEY": "Ключ OpenRouter. Активен только при LLM provider = openrouter.",
    "INFINI_OPENROUTER_MODEL": "Slug модели OpenRouter. auto оставляет выбор серверной логике/дефолту.",
    "INFINI_OPENROUTER_HTTP_REFERER": "HTTP-Referer для OpenRouter статистики/идентификации приложения.",
    "INFINI_OPENROUTER_APP_TITLE": "Название приложения для OpenRouter.",
    "INFINI_OPENAI_COMPAT_BASE_URL": "Base URL любого другого OpenAI-compatible API. Активен только при provider = openai_compat.",
    "INFINI_OPENAI_COMPAT_API_KEY": "Ключ стороннего OpenAI-compatible API.",
    "INFINI_OPENAI_COMPAT_MODEL": "Имя/slug модели стороннего OpenAI-compatible API.",
    "INFINI_LLM_FALLBACK_PROVIDER": "Опциональный fallback provider. Пусто = использовать тот же провайдер, но другую модель. Полезно, если хочешь primary OpenRouter, а fallback — local/compat.",
    "INFINI_LLM_FALLBACK_MODEL": "Опциональная запасная модель. Если основная модель умерла по бабкам/quota/auth или два раза подряд не достучалась по сети, сервер переключится на эту модель.",
    "INFINI_LLM_FALLBACK_BASE_URL": "Опциональный base URL fallback-маршрута. Пусто = брать URL выбранного fallback provider из основных полей.",
    "INFINI_LLM_FALLBACK_API_KEY": "Опциональный отдельный ключ для fallback-маршрута. Пусто = использовать основной ключ соответствующего provider.",
    "INFINI_LLM_FALLBACK_NETWORK_FAILS": "Сколько сетевых/timeout сбоев подряд терпеть на primary, прежде чем переключаться на fallback. По умолчанию 2.",
    "INFINI_LLM_RESPONSE_FORMAT": "Как просить JSON у модели. auto — безопасный дефолт; strict schema может ломаться на провайдерах без поддержки response_format.",
    "INFINI_LLM_TEMPERATURE": "Температура основного LLM planner: выше = больше вариативности/риска, ниже = стабильнее/однообразнее. Это не Z-Image; картинки регулируются seed/CFG/steps/flow-shift.",
    "INFINI_VISUAL_DIRECTOR_TEMPERATURE": "Температура LLM Visual Director, который пишет visual kit/prompt-ы для Z-Image. Выше = больше художественной вариативности, но больше риск ухода от предмета.",
    "INFINI_LLM_MAX_TOKENS": "Лимит ответа LLM. Для reasoning-моделей нужен запас, иначе модель может не успеть вернуть JSON.",
    "INFINI_BALANCE_MODE": "Режим пост-авторского баланса: safety сохраняет authored значения и применяет только технические guards; normalize включает старую мягкую нормализацию; report оставляет рекомендации и C# hard clamps.",
    "INFINI_LLM_REASONING_MODE": "Управляет reasoning/thinking API у OpenRouter или prompt-only приватной проверкой для локалок.",
    "INFINI_LLM_REASONING_MAX_TOKENS": "Бюджет thinking-токенов. Работает только когда reasoning mode = tokens и провайдер поддерживает reasoning object.",
    "INFINI_LLM_REASONING_EXCLUDE": "Просит провайдера не возвращать reasoning в content. Нужен только для API reasoning, чтобы не ломать JSON-парсер.",
    "INFINI_LLM_LOCAL_REASONING_PROMPT": "Разрешает локальной модели короткую приватную самопроверку через system prompt. Это не API thinking и не вывод chain-of-thought.",

    "INFINI_IMAGE_BACKEND": "Кто рисует PNG: локальный sd.cpp/Z-Image, внешний Image API, A1111, ComfyUI или выключено.",
    "INFINI_SDCPP_SERVER_EXE": "Путь до sd-server.exe из stable-diffusion.cpp. Активен только при image backend = sdcpp.",
    "INFINI_SDCPP_ROCM_COMPAT_ROOT": "Изолированная папка hybrid sd.cpp с HIP6-compatible DLL и rocblas/library. Переменные ROCm передаются только дочернему sd-server.exe.",
    "INFINI_SDCPP_MODEL": "Главная diffusion-модель sd.cpp: FLUX.2 Klein или Z-Image *.gguf.",
    "INFINI_SDCPP_VAE": "AE/VAE файл для выбранной модели, обычно ae.safetensors. GUI сам добавит --vae.",
    "INFINI_SDCPP_LLM": "Qwen/LLM text encoder для выбранной модели. GUI сам добавит --llm.",
    "INFINI_SDCPP_LORA_DIR": "Скрытое служебное поле. В GUI больше не редактируется: папка для --lora-model-dir автоматически выводится из выбранного LoRA file.",
    "INFINI_SDCPP_LORA_FILE": "Конкретный файл LoRA (*.safetensors/*.ckpt/*.pt/*.pth). GUI сам возьмёт родительскую папку для --lora-model-dir и имя файла для <lora:name:weight>.",
    "INFINI_SDCPP_LORA_WEIGHT": "Вес LoRA для кнопки Use selected LoRA. Обычно 0.35-0.8; для sprite style лучше начинать с 0.45-0.65.",
    "INFINI_SDCPP_LORA_PROMPT_TAGS": "Активные LoRA-теги, которые будут добавляться к каждому image prompt. Обычно заполняются кнопкой Use selected LoRA; руками нужно только для нескольких LoRA.",
    "INFINI_SDCPP_SERVER_URL": "URL уже запущенного sd.cpp server. Если autostart=1, GUI/server.py стартует его сам.",
    "INFINI_SDCPP_SERVER_AUTOSTART": "1 — server.py сам поднимет sd.cpp перед генерацией. 0 — считаем, что sd.cpp уже запущен вручную.",
    "INFINI_SDCPP_SERVER_COMMAND_MODE": "safe_args = GUI/server.py собирают argv сами и не дают pipeline preset сломать флаги. template = использовать ручной шаблон команды для нестандартных форков sd.cpp.",
    "INFINI_SDCPP_SERVER_COMMAND_TEMPLATE": "Шаблон команды запуска sd.cpp. В safe_args режиме хранится как reference/fallback; реально используется только command mode = template.",
    "INFINI_SDCPP_SERVER_EXTRA_ARGS": "Только дополнительные флаги sd.cpp: -v, --backend/--params-backend, --offload-to-cpu, cache и т.п. VAE/Qwen лучше задавать отдельными полями.",
    "INFINI_SDCPP_SERVER_SHOW_CONSOLE": "1 — открыть видимое окно sd-server.exe на Windows; 0 — писать stdout/stderr в лог.",
    "INFINI_SDCPP_SERVER_LOG_FILE": "Куда писать лог sd.cpp, если консоль выключена.",
    "INFINI_SDCPP_WIDTH": "Ширина сырого image gen. Для Terraria-иконок обычно 512 достаточно.",
    "INFINI_SDCPP_HEIGHT": "Высота сырого image gen. Обычно квадрат 512x512.",
    "INFINI_SDCPP_STEPS": "Количество шагов генерации. У turbo-моделей обычно мало шагов: 6–12.",
    "INFINI_SDCPP_CFG": "CFG scale. Для Z-Image turbo часто около 1.0.",
    "INFINI_SDCPP_SAMPLER": "Сэмплер sd.cpp. Для текущего Z-Image дефолт euler.",
    "INFINI_SDCPP_SEED": "Seed для sd.cpp. -1 = случайный seed на каждую картинку; положительное число = воспроизводимость для дебага.",
    "INFINI_ZIMAGE_PROMPT_CONTRACT": "auto = включать Z-Image prompt contract при Z-Image модели; 1 = force; 0 = отключить. Обычно auto.",
    "INFINI_ZIMAGE_POSITIVE_ONLY": "1 = для Z-Image держать negative_prompt пустым и всё упаковывать в positive prompt. Обычно включено.",
    "INFINI_IMAGE_API_BASE_URL": "Base URL внешнего Image API. Активно только при image backend = image_api.",
    "INFINI_IMAGE_API_KEY": "Ключ внешнего Image API.",
    "INFINI_IMAGE_API_MODEL": "Модель внешнего Image API.",
    "INFINI_IMAGE_API_PATH": "Путь endpoint генерации изображений, обычно /images/generations.",
    "INFINI_IMAGE_API_SIZE": "Размер сырой картинки от внешнего API до sprite postprocess.",
    "INFINI_IMAGE_API_TIMEOUT": "Сколько ждать внешний Image API.",
    "INFINI_A1111_URL": "URL Automatic1111. Активен только при image backend = a1111.",
    "INFINI_COMFYUI_URL": "URL ComfyUI. Активен только при image backend = comfyui.",

    "INFINI_VISUAL_ASSET_MODE": "Сколько визуальных ассетов генерировать: полный набор, только projectile или вообще отключить визуал.",
    "INFINI_VISUAL_DIRECTOR_LLM": "Разрешает LLM сформировать visual kit/направление для PNG, вместо голой генерации по имени.",
    "INFINI_VISUAL_DIRECTOR_MAX_TOKENS": "Лимит output tokens для шага Visual Director (LLM, который пишет visual kit/prompt'ы для Z-Image). Пусто = наследовать общий Max answer tokens.",
    "INFINI_SPRITE_MASTER_CANVAS": "Промежуточный большой RGBA-canvas (обычно 256), на который спрайт сначала нормализуется после вырезания фона, а уже потом печётся в 32/48/64. Это нужно, чтобы high-res fake pixel-art не деградировал от прямого 512→32 resize.",
    "INFINI_VISUAL_GENERATE_PROJECTILE_IMAGES": "Разрешить модели отдельный projectile PNG. Флаг не принуждает генерацию без authored baked_sprite.",
    "INFINI_VISUAL_GENERATE_IMPACT_IMAGES": "Разрешить модели отдельный impact PNG. Обычные удары рисуются VFX/Dust без PNG.",
    "INFINI_VISUAL_GENERATE_CHILD_FIELD_IMAGES": "Разрешить модели отдельные child/field PNG. Искры/поля по умолчанию идут через VFX, не через force-картинки.",
    "INFINI_VFX_LLM_DIRECTOR": "Разрешает LLM описывать VFX-слоты/намерение, но код всё равно валидирует контракт.",
    "INFINI_REMOVE_BG": "Удалять фон у сырой картинки перед запеканием sprite PNG.",
    "INFINI_BG_REMOVE_MODE": "Метод удаления фона. Оставлен только sprite_keyer — рабочий протокол для Terraria/fake pixel-art.",
    "INFINI_BG_COLOR": "Ожидаемый chroma-key/фон. Для Z-Image пайплайна обычно magenta.",
    "INFINI_SPRITE_RETRIES": "Сколько раз ретраить image gen, если техническая валидация PNG не прошла.",
    "INFINI_SPRITE_PROCESSING_PROFILE": "Профиль запекания PNG. Оставлены только: master_soft (новый дефолт), pixel_strict и legacy_nearest.",
    "INFINI_SPRITE_MASTER_CANVAS": "Промежуточный RGBA canvas перед финальным 32/48/64. Используется master-first профилями.",
    "INFINI_SPRITE_DOWNSCALE_FILTER": "Фильтр финального downscale. Игнорируется в pixel_strict/legacy_nearest, потому что там принудительный nearest.",
    "INFINI_SPRITE_PREMULTIPLIED_RESIZE": "Premultiplied RGBA resize, чтобы прозрачный magenta не подтекал в края. Не работает при nearest.",
    "INFINI_SPRITE_CHROMA_DEFRINGE": "Консервативно удаляет magenta/key-остатки на краях альфы.",
    "INFINI_PIXEL_POSTERIZE": "Сжимает видимую часть sprite в ограниченную палитру после resize.",
    "INFINI_MAX_COLORS": "Максимум цветов при posterize. Активно только если Posterize=1.",
    "INFINI_VISUAL_STRICT_AI_AUTHORSHIP": "1 — код не рисует за нейронку, только чистит/валидирует/ретраит. Это основной режим авторства модели.",
    "INFINI_VISUAL_ALLOW_PROCEDURAL_FALLBACK": "Разрешает процедурный запасной PNG, если image gen умер. Должен быть выключен при strict AI authorship.",
}

OPTION_HELP = {
    "INFINI_LLM_PROVIDER": {
        "local": "Локальная LLM через LM Studio/Ollama/OpenAI-compatible endpoint. Активны LM Studio URL/model, OpenRouter/Compat поля блокируются.",
        "openrouter": "LLM-контракт пишет модель с OpenRouter. Активны OpenRouter key/model/referer/title, локальные/compat поля блокируются.",
        "openai_compat": "Любой другой OpenAI-compatible API. Активны compat base URL/key/model.",
    },
    "INFINI_BALANCE_MODE": {
        "safety": "Дефолт: authored damage/stats сохраняются; Python ограничивает только технически опасные projectile-параметры, C# hard clamps остаются активны.",
        "normalize": "Старое поведение: дополнительно применять stage/DPS и equipment soft budgets.",
        "report": "Диагностика: Python soft balance и runtime safety corridor не мутируют значения; рекомендации пишутся в balanceReport, C# hard clamps остаются.",
    },
    "INFINI_LLM_RESPONSE_FORMAT": {
        "auto": "Дефолт: сервер сам выбирает безопасный формат под провайдера/модель.",
        "json_schema": "Просить строгую JSON schema. Хорошо для совместимых API, но некоторые локалки/провайдеры падают.",
        "json_object": "Просить JSON object без полной schema. Мягче, чем json_schema.",
        "off": "Не отправлять response_format; остаётся только prompt-инструкция вернуть JSON.",
    },
    "INFINI_LLM_REASONING_MODE": {
        "off": "Reasoning выключен. Самый совместимый режим.",
        "auto": "Для OpenRouter отправляет enabled reasoning; для local не шлёт API-поле.",
        "none": "Просит effort=none у reasoning API, если провайдер поддерживает.",
        "minimal": "Минимальный reasoning effort для поддерживаемых API.",
        "low": "Низкий reasoning effort.",
        "medium": "Средний reasoning effort; дороже по токенам, но может лучше держать контракт.",
        "high": "Высокий reasoning effort; может съесть бюджет ответа.",
        "xhigh": "Максимальный effort у провайдеров, где он есть. Риск не успеть вернуть JSON при малом max tokens.",
        "tokens": "Задать отдельный бюджет thinking через Reasoning token budget.",
        "prompt_light": "Не API reasoning: короткая приватная самопроверка в system prompt. Полезно локалкам.",
        "prompt_strong": "Не API reasoning: более сильная приватная проверка в prompt. Может слегка удлинить ответ локалки.",
    },
    "INFINI_IMAGE_BACKEND": {
        "sdcpp": "Локальный stable-diffusion.cpp/Z-Image. Активируются sd.cpp пути, размеры, steps/cfg/sampler и debug-кнопки.",
        "image_api": "Внешний OpenAI-compatible Image API. sd.cpp поля блокируются.",
        "off": "PNG не генерируются. Визуальные и sprite-processing настройки блокируются, потому что обрабатывать нечего.",
        "comfyui": "ComfyUI endpoint. Активен только URL ComfyUI; sd.cpp/Image API поля блокируются.",
        "a1111": "Automatic1111 endpoint. Активен только A1111 URL; sd.cpp/Image API поля блокируются.",
    },
    "INFINI_SDCPP_SERVER_AUTOSTART": {
        "1": "server.py сам запускает sd-server.exe перед генерацией.",
        "0": "sd.cpp должен быть уже запущен руками или отдельным bat-файлом.",
    },
    "INFINI_SDCPP_SERVER_SHOW_CONSOLE": {
        "1": "Показывать отдельное окно sd-server.exe с живым логом.",
        "0": "Не показывать консоль, писать лог в файл.",
    },
    "INFINI_SDCPP_SERVER_COMMAND_MODE": {
        "safe_args": "Рекомендуется: GUI/server.py собирает argv напрямую без shell-template, поэтому пресеты не могут испортить флаги.",
        "template": "Ручной шаблон команды. Использовать только для нестандартного sd.cpp/launcher.",
    },
    "INFINI_ZIMAGE_PROMPT_CONTRACT": {
        "auto": "Рекомендуется: включать Z-Image contract только когда backend похож на Z-Image.",
        "1": "Принудительно включить Z-Image prompt contract.",
        "0": "Отключить contract для нестандартного backend/эксперимента.",
    },
    "INFINI_ZIMAGE_POSITIVE_ONLY": {
        "1": "Рекомендуется для Z-Image Turbo: negative_prompt пустой, все техусловия в positive prompt.",
        "0": "Передавать negative_prompt как обычному SD backend'у.",
    },
    "INFINI_IMAGE_API_SIZE": {
        "512x512": "Быстро и достаточно для Terraria-иконок; потом всё равно запекается в 32/48/64.",
        "768x768": "Больше деталей и дороже/медленнее. Может помочь сложным силуэтам.",
        "1024x1024": "Максимум деталей, но тяжелее и не всегда лучше для маленькой иконки.",
    },
    "INFINI_VISUAL_ASSET_MODE": {
        "full": "Полный визуальный пакет: item + projectile/impact/child/field там, где они нужны.",
        "projectile": "Урезанный режим: item/projectile, без impact и child/field ассетов.",
        "off": "Визуальный asset pipeline выключен.",
    },
    "INFINI_BG_REMOVE_MODE": {
        "sprite_keyer": "Единственный рабочий режим удаления фона: Photoshop-like selection/keying под Terraria/fake pixel-art.",
    },
    "INFINI_BG_COLOR": {
        "magenta": "Классический #ff00ff chroma-key. Лучший дефолт для Z-Image sprite prompt.",
        "transparent": "Ожидать уже прозрачный PNG от backend.",
        "white": "Белый фон; риск снести светлые детали предмета.",
        "black": "Чёрный фон; риск снести тёмные детали предмета.",
    },
    "INFINI_SPRITE_PROCESSING_PROFILE": {
        "master_soft": "Новый дефолт: full-res cleanup → master canvas → мягкий BOX/Lanczos/Bicubic bake. Лучший для Z-Image/fake pixel-art.",
        "pixel_strict": "Master-first, но финальный resize принудительно NEAREST. Жёстче пиксели, хуже для шумного fake pixel-art.",
        "legacy_nearest": "Старый откат: прямой fit_to_canvas nearest без master-first bake. Нужен для сравнения/аварийного rollback.",
    },
    "INFINI_SPRITE_DOWNSCALE_FILTER": {
        "box": "Дефолт для fake pixel-art: усредняет high-res блоки и меньше ловит случайный шум.",
        "lanczos": "Более резкий качественный downscale, может давать ореолы на мелкой 32x32 иконке.",
        "bicubic": "Компромисс между box и lanczos.",
        "nearest": "Жёсткий пиксельный resize. В pixel_strict/legacy используется принудительно.",
    },
    "INFINI_PIXEL_POSTERIZE": {
        "1": "После resize ужать видимую часть в ограниченную палитру.",
        "0": "Оставить цвета как есть после resize.",
    },
    "INFINI_VISUAL_STRICT_AI_AUTHORSHIP": {
        "1": "Код не придумывает арт сам. Только техническая очистка, нормализация, валидация и retry.",
        "0": "Разрешить менее строгий режим; тогда можно включить procedural fallback.",
    },
    "INFINI_VISUAL_ALLOW_PROCEDURAL_FALLBACK": {
        "0": "Не подменять art генератор процедурной заглушкой. Рекомендуется для авторства ИИ.",
        "1": "Разрешить процедурный emergency PNG при провале image backend. Блокируется при strict AI authorship=1.",
    },
}

for _bool_key in [
    "INFINI_VISUAL_DIRECTOR_LLM",
    "INFINI_VISUAL_GENERATE_PROJECTILE_IMAGES",
    "INFINI_VISUAL_GENERATE_IMPACT_IMAGES",
    "INFINI_VISUAL_GENERATE_CHILD_FIELD_IMAGES",
    "INFINI_VFX_LLM_DIRECTOR",
    "INFINI_REMOVE_BG",
    "INFINI_SPRITE_PREMULTIPLIED_RESIZE",
    "INFINI_SPRITE_CHROMA_DEFRINGE",
    "INFINI_LLM_REASONING_EXCLUDE",
    "INFINI_LLM_LOCAL_REASONING_PROMPT",
    "INFINI_TRACE_PROMPTS",
]:
    OPTION_HELP.setdefault(_bool_key, {"1": "Включено.", "0": "Выключено."})

__all__ = [
    "FIELD_ORDER",
    "SDCPP_DEFAULT_COMMAND_TEMPLATE",
    "SDCPP_EXTRA_PROFILES",
    "SDCPP_EXTRA_PROFILE_HELP",
    "SDCPP_EXTRA_FLAG_SPECS",
    "repair_sdcpp_command_template",
    "DEFAULTS",
    "PRESETS",
    "PRESET_HELP",
    "FIELD_HELP",
    "OPTION_HELP",
]
