from __future__ import annotations

from pathlib import Path

from infini_local.desktop.settings_schema import DEFAULTS, FIELD_ORDER


# AGENT MAP: config.env parser/writer for the desktop GUI.
# Keep file-format compatibility here; settings_gui.py should only call these helpers.

def parse_env(path: Path) -> dict[str, str]:
    data = dict(DEFAULTS)
    if not path.exists():
        return data
    for raw in path.read_text(encoding="utf-8-sig", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            data[key] = value
    return data


def quote_env_value(value: str) -> str:
    value = str(value or "")
    if any(ch in value for ch in ['#', '\n', '\r']):
        value = value.replace('"', '\\"')
        return f'"{value}"'
    return value


def write_env(path: Path, data: dict[str, str]) -> None:
    lines = [
        "# InfiniCrafterLocal config.env",
        "# Generated by LocalGenerator/settings_gui.py. Можно править руками, но проще через GUI.",
        "",
        "# ===== LLM =====",
    ]
    sections = {
        "INFINI_IMAGE_BACKEND": "# ===== IMAGE =====",
        "INFINI_VISUAL_ASSET_MODE": "# ===== VISUAL / VFX =====",
        "INFINI_HOST": "# ===== SERVER / MULTIPLAYER =====",
        "INFINI_TRACE_PROMPTS": "# ===== TRACE / DEBUG =====",
    }
    for key in FIELD_ORDER:
        if key in sections:
            lines += ["", sections[key]]
        lines.append(f"{key}={quote_env_value(data.get(key, DEFAULTS.get(key, '')))}")
    unknown = {k: v for k, v in data.items() if k not in FIELD_ORDER}
    if unknown:
        lines += ["", "# ===== UNKNOWN / MANUAL KEYS PRESERVED ====="]
        for key in sorted(unknown):
            lines.append(f"{key}={quote_env_value(unknown[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


__all__ = [
    "parse_env",
    "quote_env_value",
    "write_env",
]
