#!/usr/bin/env python3
"""Generate C# safety bounds from canonical Author equipment primitives."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "LocalGenerator"))
from infini_local.core.runtime_authoring.capability_registry import (  # noqa: E402
    CAPABILITY_REGISTRY, LEGACY_EQUIPMENT_CLASS_DAMAGE_BOUNDS,
)

OUTPUT = ROOT / "ModSources/InfiniCrafterLocal/Common/Models/GeneratedEquipmentBounds.g.cs"


def _literal(value: int | float, *, integer: bool) -> str:
    return str(int(value)) if integer else f"{format(float(value), '.8g')}f"


def render() -> str:
    rows = [
        "// Generated by tools/generate_equipment_bounds.py; do not edit by hand.",
        "#nullable enable", "using System;", "", "namespace InfiniCrafterLocal.Common.Models;", "",
        "internal static class GeneratedEquipmentBounds", "{",
    ]
    for capability, cls in (("configure_accessory", "AccessorySpec"),
                            ("configure_armor", "ArmorSpec")):
        rows.append(f"    internal static void Normalize({cls} a)")
        rows.append("    {")
        seen: set[str] = set()
        for name, spec in sorted(CAPABILITY_REGISTRY[capability].params.items()):
            if spec.kind not in ("number", "integer"):
                continue
            wire = spec.wire_name or name
            if wire in seen:
                raise ValueError(f"duplicate {capability}.{wire}")
            seen.add(wire)
            low, high = spec.runtime_minimum, spec.runtime_maximum
            if low is None and high is None:
                continue  # No historical DTO clamp: preserve already-saved numeric values.
            if low is None or high is None:
                raise ValueError(f"incomplete legacy safety envelope: {capability}.{name}")
            if low > spec.to_wire(spec.minimum) or high < spec.to_wire(spec.maximum):
                raise ValueError(f"runtime envelope narrows Author: {capability}.{name}")
            member = wire[0].upper() + wire[1:]
            # Author decimals can lower to an integer DTO (e.g. HP/s × 2).
            # Select C# overloads from the declared wire projection, not Author kind.
            wire_integer = spec.kind == "integer" or spec.wire_multiplier != 1
            rows.append(f"        a.{member} = Math.Clamp(a.{member}, "
                        f"{_literal(low, integer=wire_integer)}, "
                        f"{_literal(high, integer=wire_integer)});")
        group = capability.removeprefix("configure_")
        class_bonus = CAPABILITY_REGISTRY["add_equipment_damage_bonus"]
        bonus = class_bonus.params["bonusPercent"]
        for wire, (low, high) in sorted(LEGACY_EQUIPMENT_CLASS_DAMAGE_BOUNDS[group].items()):
            if wire in seen or f"{group}.{wire}" not in class_bonus.final_wire_paths:
                raise ValueError(f"legacy equipment clamp lacks an exact class modifier projection: {group}.{wire}")
            if low > bonus.to_wire(bonus.minimum) or high < bonus.to_wire(bonus.maximum):
                raise ValueError(f"legacy equipment clamp narrows typed Author: {group}.{wire}")
            member = wire[0].upper() + wire[1:]
            rows.append(f"        a.{member} = Math.Clamp(a.{member}, "
                        f"{_literal(low, integer=False)}, {_literal(high, integer=False)});")
        rows.append("    }")
        rows.append("")
    rows.extend(("}", ""))
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated equipment bounds: {OUTPUT}", file=sys.stderr)
            return 1
    else:
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
